version: "3"
services:
  stock_api:
    build:
      context: ../
      dockerfile: ./devOps/prod.Dockerfile
    container_name: stock_api
    command:
      bash -c "gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    restart: always
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - nginx_network
      - local-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - local-network

  celery_worker:
    build:
      context: ../
      dockerfile: ./devOps/celery.Dockerfile
    restart: always
    container_name: stock_api_worker
    command:
      bash -c "celery -A core worker -P eventlet "
    networks:
      - local-network

  celery_beat:
    build:
      context: ../
      dockerfile: ./devOps/celery.Dockerfile
    restart: always
    container_name: stock_api_worker
    command:
      bash -c "celery -A core worker -P eventlet "
    networks:
      - local-network

  db:
    image: postgres
    restart: always
    container_name: stocks_db
    env_file:
      - db.prod.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - local-network

networks:
  nginx_network:
    external: true
  local-network:

volumes:
  pgdata: