version: "3"

services:
  stock-api:
    image: stock_api
    build:
      context: ../
      dockerfile: ./devOps/dev.Dockerfile

    container_name: stock_api
    ports:
      - "8080:8080"
    networks:
      - app-internal-net
    depends_on:
      - stocks_db
      - chrome
      - celery_worker

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    hostname: chrome
    privileged: true
    shm_size: 2g
    ports:
      - "4444:4444"
    networks:
      - app-internal-net

  celery_worker:
    image: celery_worker
    build:
      context: ../
      dockerfile: ./devOps/celery.Dockerfile
    networks:
      - app-internal-net
    restart: always
    container_name: stock_api_worker
    command:
      bash -c "celery -A core worker --loglevel=INFO -P eventlet "

  celery_beat:
    image: celery_beat
    build:
      context: ../
      dockerfile: ./devOps/celery.Dockerfile
    networks:
      - app-internal-net
    restart: always
    container_name: stock_api_beat
    command:
      bash -c "celery -A core beat "

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - app-internal-net
  stocks_db:
    image: postgres
    restart: always
    container_name: stocks_db
    env_file:
      - db.dev.env
    volumes:
      -  pgdata:/var/lib/postgresql/data
    networks:
      - app-internal-net

networks:
  app-internal-net:
    external: true

volumes:
  pgdata: