version: "3"
services:
  api:
    build: .
    container_name: stock_api
    command:
      bash -c "cd stock_web_scrapper && python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    networks:
      - local-network

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - local-network

  celery_worker:
    build: .
    restart: always
    container_name: stock_api_worker
    command:
      bash -c " cd stock_web_scrapper && celery -A core worker --loglevel=INFO -P eventlet "
    networks:
      - local-network

  celery_beat:
    build: .
    restart: always
    container_name: stock_api_beat
    command:
      bash -c " cd stock_web_scrapper && celery -A core beat "
    networks:
      - local-network

networks:
  local-network:
    name: container_network
    external: true