# Generated by Django 4.2.3 on 2023-08-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_full_name', models.CharField(help_text='Full Name of the Company', max_length=200)),
                ('company_abbreviation', models.CharField(help_text='Company Abbreviation', max_length=10, unique=True)),
                ('index', models.CharField(help_text='Company Stock Exchange Market Index', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Stock Price Date')),
                ('open_price', models.DecimalField(decimal_places=2, help_text='Day Open Price', max_digits=15)),
                ('max_price', models.DecimalField(decimal_places=2, help_text='Day Max Price', max_digits=15)),
                ('min_price', models.DecimalField(decimal_places=2, help_text='Day Min Price', max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=2, help_text='Day Close Price', max_digits=15)),
                ('volume', models.BigIntegerField(help_text='Day Volume')),
                ('company_abbreviation', models.ForeignKey(help_text='Company Abbreviation', on_delete=django.db.models.deletion.CASCADE, to='scrapper.stockcompanies', to_field='company_abbreviation')),
            ],
        ),
    ]
