# Generated by Django 4.2.3 on 2024-03-17 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indexes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Index ticker', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Stock Price Date')),
                ('open_price', models.DecimalField(decimal_places=2, help_text='Day Open Price', max_digits=15)),
                ('max_price', models.DecimalField(decimal_places=2, help_text='Day Max Price', max_digits=15)),
                ('min_price', models.DecimalField(decimal_places=2, help_text='Day Min Price', max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=2, help_text='Day Close Price', max_digits=15)),
                ('volume', models.BigIntegerField(help_text='Day Volume')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_result', to='scrapper.indexes', to_field='ticker')),
            ],
        ),
    ]
